<div class="cp-app-container" data-app="timezone">
    <div class="current-page-name">
        <div class="lp">
            <h2>
                TimeZone
            </h2>
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo cl_link('admin_panel'); ?>">
                        Control panel
                    </a>
                </li>
                <li class="active">
                    <a href="javascript:void(0);">
                        TimeZone settings
                    </a>
                </li> 
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Manage TimeZone settings
                    </h2>
                </div>
                <div class="body">
                    <form class="form" data-an="form">
                        <div class="form-group" data-an="timezone-input">
                            <label>
                                Timezone
                            </label>
                            <div class="form-line">
                                <select name="timezone" class="form-control selectpicker" data-size="10">
                                    <?php foreach ($cl["timezones"] as $tzn => $tzc): ?>
                                        <option value="<?php echo($tzn); ?>" <?php if($cl['config']['timezone'] == $tzn) { echo('selected'); } ?>>
                                            <?php echo($tzn); ?> / <small><?php echo($tzc); ?></small>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                       <div class="form-group no-mb">
                       		<button data-an="submit-ctrl" type="submit" class="btn bg-blue btn-block btn-lg waves-effect ttup">
                                Save changes
                            </button>
                       </div>
                        <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'],'none'); ?>" name="hash">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo cl_template('cpanel/assets/timezone/scripts/app_master_script'); ?>